version: "3"

services: 
  brian_php: 
    build:
      context: ./docker/php
    container_name: brian_php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - KERNEL_CLASS=${KERNEL_CLASS}
      - DATABASE_URL=${DATABASE_URL}            
    volumes:
      - ./source:/var/www

  brian_nginx: 
    build: 
      context: ./docker/nginx
    container_name: brian_nginx
    ports:
      - "80:80"
    depends_on:
      - brian_php      
    volumes:
      - ./source:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log