version: "3"

services: 
  brian_php: 
    build:
      context: ./docker/php
    container_name: brian_php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - KERNEL_CLASS=${KERNEL_CLASS}
      - DATABASE_URL=${DATABASE_URL}            
    volumes:
      - ./source:/var/www

  brian_nginx: 
    build: 
      context: ./docker/nginx
    container_name: brian_nginx
    ports:
      - "80:80"
    depends_on:
      - brian_php      
    volumes:
      - ./source:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
  
  brian_mysql:
    build:
      context: ./docker/mysql
    container_name: brian_mysql
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes: 
      - volumes/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql      
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: admin@123
  
  # brian_phpmyadmin:
  #   build: 
  #     context: ./docker/phpmyadmin
  #   container_name: brian_phpmyadmin    
  #   environment:
  #     PMA_HOST: database
  #     PMA_PORT: 3306
  #     PMA_USER: admin@123
  #     PMA_PASSWORD: admin@123
  #     MYSQL_ROOT_PASSWORD: admin@123
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: admin@123
  #   ports:
  #     - "8080:80"
  #   volumes: 
  #     - /sessions
  #     - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini